### PR TITLE
JSInterop fixes

### PR DESCRIPTION
**Pull request by martinwhitman**
Per @murlokito: the previous polling for connected status has been replaced with JSinterop-using events; jslib/src/index.ts has a class to abstract the wallet adapters and a unified signTransaction process. I wrote a process that is now commented out that has that class check if the adapter has signMessage or not, but there was a comment from @ jordaaash on discord that made me think it was more appropriate to just unify them under signTransaction. If you use Phantom's signMessage the wallet will show the message text (with interpolated nonsense characters) so that can be reversed/expanded.

### CODE REVIEW

**Comment by hoakbuilds** [comment]
Backtracking on this, I think this is a matter of just cleaning up some of the unnecessary and commented out code and we can ship it as is. This is something that will only be "perfected" with time and for that we need to actively try to build some dapps using it as a base so we can see what needs to be improved and then we'll move on from there, thoughts?

**Comment by martinwhitman** [comment]
The only other thing I wanted to add was a button to "sign message" if available, per some of the comments on Discord. Regardless, do I close this one and create another PR with the changes?

**Comment by hoakbuilds** [comment]
I think you can do it all in this one.

- Adding the `Sign Message` button
- Cleaning up code comments and other unnecessary code

**Comment by martinwhitman** [comment]
Sign message button added, comments deleted/cleaned, unnecessary code removed

**Review by hoakbuilds — APPROVED** [review]
Let's get this merged! Great effort Martin :)

**Pull request merged**
